on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH to EC2 and run commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}
          script: |
            echo "Connecting to EC2!"
            echo "Updating EC2 server"
            sudo apt update -y
            echo "stopping ngins"
            sudo systemctl stop nginx
            echo "starting nginx"
            sudo systemctl start nginx
            echo "Removing backend folder if it exist earlier"
            sudo rm -rf backend
            echo "Cloning to GITHUB"
            git clone https://github.com/muhammadwamiq/backend.git
            echo "listing files of current directiory"
            ls
            echo "Moved inside project folder"
            cd backend
            echo "installing dependencies" 
            sudo npm install
            echo "starting node app in background"
            pm2 start app.js -f --name "backend"
            echo "saving pm2"
            pm2 save
            echo "nginx reloadeding"
            sudo systemctl reload nginx
